# Generated by Django 5.2 on 2025-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Driver name')),
                ('abilities', models.IntegerField(verbose_name='Abilities')),
                ('weakness', models.IntegerField(verbose_name='Weakness')),
                ('accident_historic', models.IntegerField(verbose_name='Accident Historic')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
            },
        ),
    ]
