# Generated by Django 5.2 on 2025-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargomodel',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume (m³)'),
        ),
        migrations.AlterField(
            model_name='cargomodel',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
    ]
